# Spring
# ==================================================================

spring:
  main.banner-mode: off
  profiles.active: default

# Server
# ==================================================================

server.port: 8000
