# Server
# ==================================================================

server.port: 8000

# Database
# ==================================================================

database:

  # Choose one database url
  # Replace variables between < and >
  # Remove < and >

  # H2 (File)
  # url: "r2dbc:h2:file:///<./path/tally>"

  # H2 (In-Memory)
  url: r2dbc:h2:mem:///tally?options=DB_CLOSE_DELAY=-1;

  # Postgres
  # url: "r2dbc:postgresql://<user>:<password>@<host>:<port>/<database>?schema=<schema>"

# JWT
# ==================================================================

jwt:
  # If not set, the servers host name is used
  issuer: tally.backend

  # If not set, the app name is used
  audience: tally.app

  key: SomeMoreThen30CharactersLongString
