# App
# ==================================================================

app:
  name: ${project.parent.artifactId}
  version: ${project.version}

# Spring
# ==================================================================

spring:
  main.banner-mode: off
  profiles.active: default
